### ISSUE TITLE
Make results tables columns resizable

### ISSUE THREAD

**Issue by akkamburov** [nemesis-software/nemesis-console-v2#82]
Make columns of the table of Default Viewer results in backend consolse resizable, so that if there's longer text the user can resize it and see the whole text.
See the screenshot, at the bottom "backend_console-sampl...Samplestore" currently isn't resizable and you can see the full text w/o opening the inspector.
![backendConsole_resizable_columns](https://user-images.githubusercontent.com/24289541/70322988-4ef0ee80-1834-11ea-90ab-0af0a1994f99.png)

Additionally the full text can be shown in a tooltip balloon when the user hovers over a cell (for lets say over a second or so) , see the 2nd scrsht:
![backendConsole_table_cell_tooltip_onHover](https://user-images.githubusercontent.com/24289541/70323721-3c77b480-1836-11ea-87df-67dd72d109f5.jpg)

**Comment by ptahchiev** [comment]
Fixed.
